// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using T_Electronic.Logic.Data;

#nullable disable

namespace T_Electronic.Logic.Migrations
{
    [DbContext(typeof(T_ElectronicDbContext))]
    partial class T_ElectronicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("T_Electronic.Logic.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Computadoras"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Telefonos"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Televisor"
                        });
                });

            modelBuilder.Entity("T_Electronic.Logic.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria_Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Categoria_Id");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria_Id = 1,
                            Descripcion = "La notebook Asus TUF Gaming F15 ofrece una experiencia visual excepcional con su pantalla de 15,6 pulgadas y resolución FHD (1920 x 1080), que proporciona imágenes nítidas y colores vibrantes.",
                            Nombre = "Notebook ASUS TUF Gaming",
                            Precio = 200000m
                        },
                        new
                        {
                            Id = 2,
                            Categoria_Id = 2,
                            Descripcion = "Chip A18 potencia funcionalidades de foto y video, lo hace todo con una eficiencia energética excepcional para extender la duración de la batería. Botón control de cámara, toma la foto perfecta con sólo levantar un dedo. Nueva cámara ultra gran angular.",
                            Nombre = "Apple iPhone 16 128GB Teal",
                            Precio = 623000m
                        },
                        new
                        {
                            Id = 3,
                            Categoria_Id = 3,
                            Descripcion = "Mediante sus entradas HDMI, con la TV Samsung Smart 55 pulgadas podés conectar reproductores de audio y video; consolas de juegos y notebooks",
                            Nombre = "Lenovo LOQ Gen 9 (15\" Intel) GeForce RTX™ 2050 ",
                            Precio = 10000m
                        });
                });

            modelBuilder.Entity("T_Electronic.Logic.Models.Producto", b =>
                {
                    b.HasOne("T_Electronic.Logic.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("Categoria_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("T_Electronic.Logic.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
